### ISSUE TITLE
微信第三方平台发送模板消息

### ISSUE THREAD

**Issue by chenfengjw163** [1046102779/official_account#1]
微信第三方平台发送模板消息时，是用授权方的token调用接口，templateid也要是授权方的吧
那么是不是授权方授权第三方平台后，第三方平台还需要给每个授权方单独维护一套消息模板？

**Comment by 1046102779** [comment]
模板在微信公开的消息列表寻找自己想要的，然后添加到业务库中，在通过official_accounts服务申请。

也就是说，库里先添加一套SaaS平台想要的模板消息库，然后再让托管的公众号通过服务管理模板消息列表（包括申请、删除、发送模板消息等）

**Comment by chenfengjw163** [comment]
哦 明白了，还是需要再托管的小程序或者公众号中单独维护一份消息模板。
谢谢
